version: '3.5'
services:

  web:
    build: .
    command: bash -c 'bundle exec rake db:setup && bundle exec ruby start.rb'
    volumes:
      - .:/myapp
    depends_on:
     - db

  db:
    image: postgres
    volumes:
      - './tmp/db:/var/lib/postgresql/data'

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
