default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: codeship_monitor_development

test:
  <<: *default
  database: codeship_monitor_test
